from ChessEngine import GameState, Move
from consts import *
import pygame as pg


def loadImages():
    allPieces = ['wp', 'wR', 'wN', 'wB', 'wK', 'wQ', 'bp', 'bR', 'bN', 'bB', 'bK', 'bQ']
    for piece in allPieces:
        IMAGES[piece] = pg.transform.scale(pg.image.load(f"images/{piece}.png"), (SQUARE_SIZE, SQUARE_SIZE))


# Drawing the squares of the board.
# PS : Top Left is always white.
def drawBoard(screen):
    colors = (pg.Color(227, 193, 111), pg.Color(184, 139, 74))
    for r in range(DIMENSION):
        for c in range(DIMENSION):
            color = colors[(r + c) % 2]
            pg.draw.rect(screen, color, pg.Rect(((c * SQUARE_SIZE) + FULL_LEFT_PART_WIDTH), (r * SQUARE_SIZE), SQUARE_SIZE, SQUARE_SIZE))



# Drawing the pieces on the board.
def drawPieces(screen, board):
    for r in range(DIMENSION):
        for c in range(DIMENSION):
            # Draw the piece only if it is not an empty square
            if board[r][c] != '--':
                screen.blit(IMAGES[board[r][c]],
                            pg.Rect(((c * SQUARE_SIZE) + FULL_LEFT_PART_WIDTH), (r * SQUARE_SIZE), SQUARE_SIZE, SQUARE_SIZE))


# Drawing the left menu and the right move log menu
def drawLeftRightMenu(screen):
    # Pawn Promotion Menu
    rectDimensions = (0, 0, LEFT_MENU_WIDTH, BOARD_HEIGHT)
    pg.draw.rect(screen, pg.Color(14, 174, 107), rectDimensions)

# Draw the options if the player made a pawn promotion move
def drawPawnPromotionOptions(screen, color):
    pieces = [color + piece for piece in ['Q', 'R', 'N', 'B']]
    heightOffset = BOARD_HEIGHT - (2 * SQUARE_SIZE) if color == 'w' else 0
    idx = 0
    for r in range(2):
        for c in range(2):
            pieceRect = pg.Rect(c * SQUARE_SIZE, (r * SQUARE_SIZE) + heightOffset, SQUARE_SIZE, SQUARE_SIZE)
            screen.blit(IMAGES[pieces[idx]], pieceRect)
            idx += 1


# Draw the current game state.
def drawGameState(screen, gameState):
    drawBoard(screen)
    drawPieces(screen, gameState.board)
    drawLeftRightMenu(screen)
    drawPawnPromotionOptions(screen, 'b')
    drawPawnPromotionOptions(screen, 'w')


# Main Function
def main():
    # Setting up the board's graphics
    pg.init()
    screen = pg.display.set_mode((WINDOW_WIDTH, BOARD_HEIGHT))
    pg.display.set_caption("My Chess Engine")
    clock = pg.time.Clock()
    screen.fill("black")
    # Loading the pieces' images
    loadImages()
    gameState = GameState()
    validMoves = gameState.getValidMoves()
    moveMade = False  # Flag to detect changes whenever a move is made
    squareSelected = ()  # contains a tuple (x, y) of the selected square
    playerClicks = []  # contains at most 2 tuples : (x, y)
    running = True
    while running:
        for event in pg.event.get():
            if event.type == pg.QUIT:
                running = not running
            elif event.type == pg.MOUSEBUTTONDOWN:
                # Get the mouse position in (x, y) format
                mouse_pos_x, mouse_pos_y = pg.mouse.get_pos()
                print(mouse_pos_x, mouse_pos_y)
                # In case the click was on the board
                if 181 <= mouse_pos_x <= 837:
                    col, row = (mouse_pos_x - 180) // SQUARE_SIZE, mouse_pos_y // SQUARE_SIZE
                    # Check if the last selected square is the same as the one selected now : Undo the selection
                    if squareSelected == (row, col):
                        squareSelected = ()  # Deselect the selected square
                        playerClicks = []  # Clear the clicks
                    else:
                        squareSelected = (row, col)
                        playerClicks.append(squareSelected)
                        if len(playerClicks) == 2:  # After the 2nd move
                            print(playerClicks)
                            move = Move(playerClicks[0], playerClicks[1], gameState.board)
                            # print(move.getChessNotation())
                            for i in range(len(validMoves)):
                                if move == validMoves[i]:
                                    gameState.makeMove(validMoves[i]) # Play the move generated by the engine
                                    moveMade = True
                                    squareSelected = ()  # Deselect the selected square
                                    playerClicks = []  # Clear the clicks
                            if not moveMade:
                                playerClicks = [squareSelected]
            elif event.type == pg.KEYDOWN:
                if event.key == pg.K_z:
                    gameState.undoMove()
                    moveMade = True

        if moveMade:
            validMoves = gameState.getValidMoves()
            print(f"There are currently {len(validMoves)} valid moves .\n{'-' * 35}")
            moveMade = False

        drawGameState(screen, gameState)
        clock.tick(MAX_FPS)
        pg.display.flip()


if __name__ == "__main__":
    main()
